#!/usr/bin/env python

__author__ = "Nat Kerman"
__version__ = 0.1
# %%
from astropy.table import Table

class bcolors: # We may wish to print some colored output to the terminal
    # citation https://stackoverflow.com/questions/287871/how-to-print-colored-text-to-the-terminal
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    DKGREEN = '\033[32m'
    OKGREEN = '\033[92m'
    DKRED = '\033[31m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
# %%
def get_table_info(table_file):
    readtab = Table.read(table_file)
    print(f"{bcolors.BOLD}{bcolors.OKBLUE}{table_file} has the following columns:{bcolors.ENDC}")
    print(bcolors.DKGREEN,readtab.info,bcolors.ENDC)
    # for column in readtab.columns:
    #     print(f"{bcolors.DKGREEN}* {column}{bcolors.ENDC}" )
    print(str(readtab))
# %%
# get_table_info("/Users/nkerman/crds_cache/52m2056hl_tds.fits")

# %%

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("filelist", help="File to read", nargs="+", type=str)
    args = parser.parse_args()
    if args.filelist:
        for filename in args.filelist:
            try:
                get_table_info(filename)
            except Exception as ex:
                print(f"Failed with file: {filename}. See Exception below: \n{ex}")
